//
// Created by TD on 24-12-13.
//

#include "epiboly.h"

#include <doodle_core/metadata/kitsu/task_type.h>
#include <doodle_core/metadata/user.h>
#include <doodle_core/sqlite_orm/sqlite_database.h>

#include <doodle_lib/core/http/http_function.h>
#include <doodle_lib/core/http/json_body.h>
#include <doodle_lib/http_client/dingding_client.h>
#include <doodle_lib/http_method/kitsu/kitsu.h>
namespace doodle::http::kitsu {
namespace {
boost::asio::awaitable<boost::beast::http::message_generator> config(session_data_ptr in_handle) {
  co_return in_handle->make_msg(R"(
{
    "is_self_hosted": true,
    "crisp_token": "",
    "dark_theme_by_default": null,
    "indexer_configured": true,
    "saml_enabled": false,
    "saml_idp_name": "",
    "default_locale": "zh",
    "default_timezone": "Asia/Shanghai"
}
)"s);
}
boost::asio::awaitable<boost::beast::http::message_generator> authenticated(session_data_ptr in_handle) {
  co_return in_handle->make_error_code_msg(boost::beast::http::status::unauthorized, R"({
    "msg": "Missing JWT in cookies or headers Missing cookie \"access_token_cookie\"; Missing Authorization Header"
})"s);
}

boost::asio::awaitable<boost::beast::http::message_generator> user_context(session_data_ptr in_handle) {
  nlohmann::json l_json{};
  l_json["projects"] = nlohmann::json::parse(R"([
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.240/public/后期/WDSXTQL/",
    "code": "SX",
    "created_at": "2024-09-12T10:06:46",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "WDSXTQL",
    "end_date": "2026-12-31",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "36e1651f-714a-4b01-b3d7-40a6802ade13",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": false,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "我的师兄太强了",
    "nb_episodes": 0,
    "path": "//192.168.10.242/public/WDSXTQL",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2024-05-01",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2025-01-16T10:10:51"
  },
  {
    "asset_types": [],
    "auto_upload_path": "",
    "code": null,
    "created_at": "2024-12-19T02:09:47",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "",
    "end_date": "2031-07-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": 28,
    "homepage": "assets",
    "id": "4f7bdb5a-0efa-4474-9eba-fd43aa69aae0",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": false,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": 6,
    "man_days": null,
    "max_retakes": 0,
    "name": "我什么时候无敌了",
    "nb_episodes": 0,
    "path": "",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2024-05-31",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2025-02-12T01:32:55"
  },
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.240/public/后期/JJ_DJ/",
    "code": "JJ",
    "created_at": "2024-11-07T05:40:42",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "JingJie",
    "end_date": "2027-11-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "d41d3dae-f86b-4080-850d-3d41ef272dd2",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": false,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "镜·界",
    "nb_episodes": 0,
    "path": "//192.168.10.242/public/JJ_DJ",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "9:16",
    "resolution": "1080x1920",
    "shotgun_id": null,
    "start_date": "2024-09-01",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {
      "13ddf60c-ed8e-4e65-85bb-57dc4207aeca": 3,
      "1a1491e8-5a01-4a7f-bc78-5ee9d2a0aa9f": 4,
      "1a26b082-8cb3-4d3c-9054-50a069ac64b2": 1,
      "32504e3e-381c-4f36-bdeb-f73328f96f9c": 4,
      "3e20ff2b-13e6-4dce-8bf2-37341b5c1f34": 2,
      "9be21729-be9e-4914-afc4-6046ed089886": 3,
      "9d71918b-cbf0-46bc-9c39-27177c9a950a": 2,
      "a33b7371-038c-4628-93b2-6754fc4f302b": 5,
      "c0d5224e-70c3-4b2f-8f49-348d6e051029": 6,
      "da050d42-4f45-40c4-9638-cc637753d3b5": 5,
      "eb7c92c8-232c-4894-8efa-c62ced44ff05": 1
    },
    "team": [],
    "type": "Project",
    "updated_at": "2025-01-10T09:56:23"
  },
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.240/public/后期/SSWH/",
    "code": null,
    "created_at": "2024-09-24T11:51:32",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "SSWH",
    "end_date": "2029-12-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "b5b30840-8473-4369-9b5f-c9ee44a9ecdd",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": null,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "双生武魂",
    "nb_episodes": 0,
    "path": "//192.168.10.240/public/SSWH",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2024-01-01",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2024-12-14T09:31:48"
  },
  {
    "asset_types": [
      "f9a8be37-2d05-4e20-8fae-751a61960ce4",
      "21b3f5aa-cdd6-4fca-ace4-65077494df4b",
      "8c02b76a-6be6-4959-af58-5c31a85fe072"
    ],
    "auto_upload_path": "//192.168.10.250/public/HouQi/1-DuBuXiaoYao/1_DBXY_TiJiaoWenJian/",
    "code": "DB",
    "created_at": "2024-03-26T05:34:20",
    "data": null,
    "default_preview_background_file_id": null,
    "description": "daaas",
    "descriptors": [],
    "en_str": "DuBuXiaoYao",
    "end_date": "2027-11-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "eb2b5cde-c1cf-47a0-aba4-e196b6f774dd",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": false,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "独步逍遥",
    "nb_episodes": 0,
    "path": "//192.168.10.250/public/DuBuXiaoYao_3",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2023-11-28",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2025-01-17T01:18:44"
  },
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.240/public/后期/WuJinShenYu",
    "code": null,
    "created_at": "2024-05-11T01:43:15",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "WuJinShenYu",
    "end_date": "2029-03-01",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "d2450560-60d4-451e-aeb8-012d573117cc",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": null,
    "is_set_preview_automated": true,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "无尽神域",
    "nb_episodes": 0,
    "path": "//192.168.10.240/public/WuJinShenYu",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2022-01-01",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2025-01-08T05:13:34"
  },
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.253/public/后期/LianQiShiWanNian/",
    "code": "LQ",
    "created_at": "2024-09-24T02:03:20",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "LianQiShiWanNian",
    "end_date": "2031-12-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "c340051a-45a6-4af1-a750-efefe639c75b",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": false,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "炼气十万年",
    "nb_episodes": 0,
    "path": "//192.168.10.253/public/LianQiShiWanNian",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "short",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2021-12-31",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2025-02-12T03:27:04"
  },
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.240/public/后期/ZMLCLWDSWD/",
    "code": "ZM",
    "created_at": "2024-07-02T06:27:21",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "ZMLCLWDSWD",
    "end_date": "2027-11-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "a2a7cae0-a7ea-4ce9-a26d-2979048bcee0",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": false,
    "is_set_preview_automated": true,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "宗门里除了我都是卧底",
    "nb_episodes": 0,
    "path": "//192.168.10.240/public/ZMLCLWDSWD",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "featurefilm",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2024-12-01",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2025-01-20T07:51:57"
  },
  {
    "asset_types": [],
    "auto_upload_path": "//192.168.10.240/public/后期/WanGuShenHua/",
    "code": null,
    "created_at": "2024-09-24T11:43:47",
    "data": null,
    "default_preview_background_file_id": null,
    "description": null,
    "descriptors": [],
    "en_str": "WanGuShenHua",
    "end_date": "2029-12-30",
    "episode_span": 0,
    "file_tree": null,
    "fps": "25",
    "has_avatar": false,
    "hd_bitrate_compression": null,
    "homepage": "assets",
    "id": "0fc7196c-8fc2-45d5-a60f-822703b370ba",
    "is_clients_isolated": false,
    "is_preview_download_allowed": false,
    "is_publish_default_for_artists": null,
    "is_set_preview_automated": false,
    "ld_bitrate_compression": null,
    "man_days": null,
    "max_retakes": 0,
    "name": "万古神话",
    "nb_episodes": 0,
    "path": "//192.168.10.240/public/WanGuShenHua",
    "preview_background_files": [],
    "production_style": "3d",
    "production_type": "short",
    "project_status_id": "755c9edd-9481-4145-ab43-21491bdf2739",
    "ratio": "16:9",
    "resolution": "1920x1080",
    "shotgun_id": null,
    "start_date": "2023-10-02",
    "status_automations": [],
    "task_statuses": [],
    "task_statuses_link": {},
    "task_types": [],
    "task_types_priority": {},
    "team": [],
    "type": "Project",
    "updated_at": "2024-12-06T08:38:36"
  }
])");
  co_return in_handle->make_msg(l_json.dump());
}
}  // namespace
void epiboly_reg(http_route& in_http_route) {
  in_http_route.reg(std::make_shared<http_function>(boost::beast::http::verb::get, "api/config", config))
      .reg(std::make_shared<http_function>(boost::beast::http::verb::get, "api/auth/authenticated", authenticated))
      .reg(std::make_shared<http_function>(boost::beast::http::verb::get, "api/data/user/context", user_context));
}
}  // namespace doodle::http::kitsu