//
// Created by TD on 2021/10/14.
//

#ifndef DOODLE_SRC_DOODLE_EXE_MAYA_PLUG_GUI_MAYA_PLUG_APP_H_
#define DOODLE_SRC_DOODLE_EXE_MAYA_PLUG_GUI_MAYA_PLUG_APP_H_



class maya_plug_app {

};



#endif //DOODLE_SRC_DOODLE_EXE_MAYA_PLUG_GUI_MAYA_PLUG_APP_H_
