//
// Created by TD on 2021/11/4.
//

#ifndef DOODLE_SRC_DOODLE_LIB_FILE_WARP_OPENCV_READ_PLAYER_H_
#define DOODLE_SRC_DOODLE_LIB_FILE_WARP_OPENCV_READ_PLAYER_H_



class opencv_read_player {

};



#endif //DOODLE_SRC_DOODLE_LIB_FILE_WARP_OPENCV_READ_PLAYER_H_
