//
// Created by TD on 2022/1/18.
//

#ifndef DOODLE_SRC_DOODLE_LIB_PLATFORM_WIN_APP_BASE_H_
#define DOODLE_SRC_DOODLE_LIB_PLATFORM_WIN_APP_BASE_H_

class app_base {
};

#endif  // DOODLE_SRC_DOODLE_LIB_PLATFORM_WIN_APP_BASE_H_
