//
// Created by TD on 2021/10/14.
//

#ifndef DOODLE_SRC_DOODLE_EXE_MAYA_PLUG_GUI_WIDGETS_MAYA_TOOL_WIDGET_H_
#define DOODLE_SRC_DOODLE_EXE_MAYA_PLUG_GUI_WIDGETS_MAYA_TOOL_WIDGET_H_



class maya_tool_widget {

};



#endif //DOODLE_SRC_DOODLE_EXE_MAYA_PLUG_GUI_WIDGETS_MAYA_TOOL_WIDGET_H_
