// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata_server.proto

#include "metadata_server.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace doodle {
constexpr metadata_database_meta_type_value::metadata_database_meta_type_value(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : value_(0)
{}
struct metadata_database_meta_type_valueDefaultTypeInternal {
  constexpr metadata_database_meta_type_valueDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~metadata_database_meta_type_valueDefaultTypeInternal() {}
  union {
    metadata_database_meta_type_value _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT metadata_database_meta_type_valueDefaultTypeInternal _metadata_database_meta_type_value_default_instance_;
constexpr metadata_database::metadata_database(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : uuid_path_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , parent_(nullptr)
  , update_time_(nullptr)
  , metadata_cereal_(nullptr)
  , m_type_(nullptr)
  , id_(PROTOBUF_ULONGLONG(0)){}
struct metadata_databaseDefaultTypeInternal {
  constexpr metadata_databaseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~metadata_databaseDefaultTypeInternal() {}
  union {
    metadata_database _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT metadata_databaseDefaultTypeInternal _metadata_database_default_instance_;
constexpr metadata_database_filter::metadata_database_filter(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : begin_time_(nullptr)
  , end_time_(nullptr)
  , m_type_(nullptr)
  , parent_(nullptr)
  , id_(PROTOBUF_ULONGLONG(0)){}
struct metadata_database_filterDefaultTypeInternal {
  constexpr metadata_database_filterDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~metadata_database_filterDefaultTypeInternal() {}
  union {
    metadata_database_filter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT metadata_database_filterDefaultTypeInternal _metadata_database_filter_default_instance_;
}  // namespace doodle
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_metadata_5fserver_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_metadata_5fserver_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_metadata_5fserver_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_metadata_5fserver_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_meta_type_value, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_meta_type_value, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, id_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, uuid_path_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, parent_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, update_time_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, metadata_cereal_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database, m_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_filter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_filter, id_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_filter, begin_time_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_filter, end_time_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_filter, m_type_),
  PROTOBUF_FIELD_OFFSET(::doodle::metadata_database_filter, parent_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::doodle::metadata_database_meta_type_value)},
  { 6, -1, sizeof(::doodle::metadata_database)},
  { 17, -1, sizeof(::doodle::metadata_database_filter)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::doodle::_metadata_database_meta_type_value_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::doodle::_metadata_database_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::doodle::_metadata_database_filter_default_instance_),
};

const char descriptor_table_protodef_metadata_5fserver_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025metadata_server.proto\022\006doodle\032\037google/"
  "protobuf/timestamp.proto\032\031google/protobu"
  "f/any.proto\032\036google/protobuf/wrappers.pr"
  "oto\032\022user_message.proto\"\262\003\n\021metadata_dat"
  "abase\022\n\n\002id\030\001 \001(\004\022\021\n\tuuid_path\030\002 \001(\t\022,\n\006"
  "parent\030\003 \001(\0132\034.google.protobuf.UInt64Val"
  "ue\022/\n\013update_time\030\004 \001(\0132\032.google.protobu"
  "f.Timestamp\022-\n\017Metadata_cereal\030\005 \001(\0132\024.g"
  "oogle.protobuf.Any\0229\n\006m_type\030\006 \001(\0132).doo"
  "dle.metadata_database.meta_type_value\032E\n"
  "\017meta_type_value\0222\n\005value\030\001 \001(\0162#.doodle"
  ".metadata_database.meta_type\"n\n\tmeta_typ"
  "e\022\020\n\014unknown_file\020\000\022\020\n\014project_root\020\001\022\010\n"
  "\004file\020\002\022\n\n\006folder\020\003\022\017\n\013derive_file\020\004\022\026\n\022"
  "animation_lib_root\020\005\"\355\001\n\030metadata_databa"
  "se_filter\022\n\n\002id\030\001 \001(\004\022.\n\nbegin_time\030\002 \001("
  "\0132\032.google.protobuf.Timestamp\022,\n\010end_tim"
  "e\030\003 \001(\0132\032.google.protobuf.Timestamp\0229\n\006m"
  "_type\030\004 \001(\0132).doodle.metadata_database.m"
  "eta_type_value\022,\n\006parent\030\005 \001(\0132\034.google."
  "protobuf.UInt64Value2\350\004\n\017metadata_server"
  "\022J\n\020install_metadata\022\031.doodle.metadata_d"
  "atabase\032\031.doodle.metadata_database\"\000\022I\n\017"
  "delete_metadata\022\031.doodle.metadata_databa"
  "se\032\031.doodle.metadata_database\"\000\022I\n\017updat"
  "e_metadata\022\031.doodle.metadata_database\032\031."
  "doodle.metadata_database\"\000\022R\n\017filter_met"
  "adata\022 .doodle.metadata_database_filter\032"
  "\031.doodle.metadata_database\"\0000\001\022C\n\021instal"
  "l_user_date\022\025.doodle.user_database\032\025.doo"
  "dle.user_database\"\000\022B\n\020update_user_date\022"
  "\025.doodle.user_database\032\025.doodle.user_dat"
  "abase\"\000\022I\n\020delete_user_date\022\034.doodle.use"
  "r_database_filter\032\025.doodle.user_database"
  "\"\000\022K\n\020filter_user_date\022\034.doodle.user_dat"
  "abase_filter\032\025.doodle.user_database\"\0000\001b"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_metadata_5fserver_2eproto_deps[4] = {
  &::descriptor_table_google_2fprotobuf_2fany_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
  &::descriptor_table_user_5fmessage_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_metadata_5fserver_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_metadata_5fserver_2eproto = {
  false, false, 1447, descriptor_table_protodef_metadata_5fserver_2eproto, "metadata_server.proto", 
  &descriptor_table_metadata_5fserver_2eproto_once, descriptor_table_metadata_5fserver_2eproto_deps, 4, 3,
  schemas, file_default_instances, TableStruct_metadata_5fserver_2eproto::offsets,
  file_level_metadata_metadata_5fserver_2eproto, file_level_enum_descriptors_metadata_5fserver_2eproto, file_level_service_descriptors_metadata_5fserver_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_metadata_5fserver_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_metadata_5fserver_2eproto);
  return descriptor_table_metadata_5fserver_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_metadata_5fserver_2eproto(&descriptor_table_metadata_5fserver_2eproto);
namespace doodle {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* metadata_database_meta_type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_metadata_5fserver_2eproto);
  return file_level_enum_descriptors_metadata_5fserver_2eproto[0];
}
bool metadata_database_meta_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr metadata_database_meta_type metadata_database::unknown_file;
constexpr metadata_database_meta_type metadata_database::project_root;
constexpr metadata_database_meta_type metadata_database::file;
constexpr metadata_database_meta_type metadata_database::folder;
constexpr metadata_database_meta_type metadata_database::derive_file;
constexpr metadata_database_meta_type metadata_database::animation_lib_root;
constexpr metadata_database_meta_type metadata_database::meta_type_MIN;
constexpr metadata_database_meta_type metadata_database::meta_type_MAX;
constexpr int metadata_database::meta_type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class metadata_database_meta_type_value::_Internal {
 public:
};

metadata_database_meta_type_value::metadata_database_meta_type_value(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:doodle.metadata_database.meta_type_value)
}
metadata_database_meta_type_value::metadata_database_meta_type_value(const metadata_database_meta_type_value& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:doodle.metadata_database.meta_type_value)
}

void metadata_database_meta_type_value::SharedCtor() {
value_ = 0;
}

metadata_database_meta_type_value::~metadata_database_meta_type_value() {
  // @@protoc_insertion_point(destructor:doodle.metadata_database.meta_type_value)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void metadata_database_meta_type_value::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void metadata_database_meta_type_value::ArenaDtor(void* object) {
  metadata_database_meta_type_value* _this = reinterpret_cast< metadata_database_meta_type_value* >(object);
  (void)_this;
}
void metadata_database_meta_type_value::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void metadata_database_meta_type_value::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void metadata_database_meta_type_value::Clear() {
// @@protoc_insertion_point(message_clear_start:doodle.metadata_database.meta_type_value)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* metadata_database_meta_type_value::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .doodle.metadata_database.meta_type value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_value(static_cast<::doodle::metadata_database_meta_type>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* metadata_database_meta_type_value::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:doodle.metadata_database.meta_type_value)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .doodle.metadata_database.meta_type value = 1;
  if (this->value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doodle.metadata_database.meta_type_value)
  return target;
}

size_t metadata_database_meta_type_value::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doodle.metadata_database.meta_type_value)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .doodle.metadata_database.meta_type value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_value());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void metadata_database_meta_type_value::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doodle.metadata_database.meta_type_value)
  GOOGLE_DCHECK_NE(&from, this);
  const metadata_database_meta_type_value* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<metadata_database_meta_type_value>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doodle.metadata_database.meta_type_value)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doodle.metadata_database.meta_type_value)
    MergeFrom(*source);
  }
}

void metadata_database_meta_type_value::MergeFrom(const metadata_database_meta_type_value& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doodle.metadata_database.meta_type_value)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    _internal_set_value(from._internal_value());
  }
}

void metadata_database_meta_type_value::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doodle.metadata_database.meta_type_value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void metadata_database_meta_type_value::CopyFrom(const metadata_database_meta_type_value& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doodle.metadata_database.meta_type_value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool metadata_database_meta_type_value::IsInitialized() const {
  return true;
}

void metadata_database_meta_type_value::InternalSwap(metadata_database_meta_type_value* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(value_, other->value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata metadata_database_meta_type_value::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class metadata_database::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::UInt64Value& parent(const metadata_database* msg);
  static const PROTOBUF_NAMESPACE_ID::Timestamp& update_time(const metadata_database* msg);
  static const PROTOBUF_NAMESPACE_ID::Any& metadata_cereal(const metadata_database* msg);
  static const ::doodle::metadata_database_meta_type_value& m_type(const metadata_database* msg);
};

const PROTOBUF_NAMESPACE_ID::UInt64Value&
metadata_database::_Internal::parent(const metadata_database* msg) {
  return *msg->parent_;
}
const PROTOBUF_NAMESPACE_ID::Timestamp&
metadata_database::_Internal::update_time(const metadata_database* msg) {
  return *msg->update_time_;
}
const PROTOBUF_NAMESPACE_ID::Any&
metadata_database::_Internal::metadata_cereal(const metadata_database* msg) {
  return *msg->metadata_cereal_;
}
const ::doodle::metadata_database_meta_type_value&
metadata_database::_Internal::m_type(const metadata_database* msg) {
  return *msg->m_type_;
}
void metadata_database::clear_parent() {
  if (GetArena() == nullptr && parent_ != nullptr) {
    delete parent_;
  }
  parent_ = nullptr;
}
void metadata_database::clear_update_time() {
  if (GetArena() == nullptr && update_time_ != nullptr) {
    delete update_time_;
  }
  update_time_ = nullptr;
}
void metadata_database::clear_metadata_cereal() {
  if (GetArena() == nullptr && metadata_cereal_ != nullptr) {
    delete metadata_cereal_;
  }
  metadata_cereal_ = nullptr;
}
metadata_database::metadata_database(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:doodle.metadata_database)
}
metadata_database::metadata_database(const metadata_database& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  uuid_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_uuid_path().empty()) {
    uuid_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_uuid_path(), 
      GetArena());
  }
  if (from._internal_has_parent()) {
    parent_ = new PROTOBUF_NAMESPACE_ID::UInt64Value(*from.parent_);
  } else {
    parent_ = nullptr;
  }
  if (from._internal_has_update_time()) {
    update_time_ = new PROTOBUF_NAMESPACE_ID::Timestamp(*from.update_time_);
  } else {
    update_time_ = nullptr;
  }
  if (from._internal_has_metadata_cereal()) {
    metadata_cereal_ = new PROTOBUF_NAMESPACE_ID::Any(*from.metadata_cereal_);
  } else {
    metadata_cereal_ = nullptr;
  }
  if (from._internal_has_m_type()) {
    m_type_ = new ::doodle::metadata_database_meta_type_value(*from.m_type_);
  } else {
    m_type_ = nullptr;
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:doodle.metadata_database)
}

void metadata_database::SharedCtor() {
uuid_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&parent_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&parent_)) + sizeof(id_));
}

metadata_database::~metadata_database() {
  // @@protoc_insertion_point(destructor:doodle.metadata_database)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void metadata_database::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  uuid_path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete parent_;
  if (this != internal_default_instance()) delete update_time_;
  if (this != internal_default_instance()) delete metadata_cereal_;
  if (this != internal_default_instance()) delete m_type_;
}

void metadata_database::ArenaDtor(void* object) {
  metadata_database* _this = reinterpret_cast< metadata_database* >(object);
  (void)_this;
}
void metadata_database::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void metadata_database::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void metadata_database::Clear() {
// @@protoc_insertion_point(message_clear_start:doodle.metadata_database)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uuid_path_.ClearToEmpty();
  if (GetArena() == nullptr && parent_ != nullptr) {
    delete parent_;
  }
  parent_ = nullptr;
  if (GetArena() == nullptr && update_time_ != nullptr) {
    delete update_time_;
  }
  update_time_ = nullptr;
  if (GetArena() == nullptr && metadata_cereal_ != nullptr) {
    delete metadata_cereal_;
  }
  metadata_cereal_ = nullptr;
  if (GetArena() == nullptr && m_type_ != nullptr) {
    delete m_type_;
  }
  m_type_ = nullptr;
  id_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* metadata_database::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string uuid_path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_uuid_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "doodle.metadata_database.uuid_path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.UInt64Value parent = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_parent(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp update_time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_update_time(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Any Metadata_cereal = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_metadata_cereal(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .doodle.metadata_database.meta_type_value m_type = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_m_type(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* metadata_database::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:doodle.metadata_database)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // string uuid_path = 2;
  if (this->uuid_path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_uuid_path().data(), static_cast<int>(this->_internal_uuid_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "doodle.metadata_database.uuid_path");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_uuid_path(), target);
  }

  // .google.protobuf.UInt64Value parent = 3;
  if (this->has_parent()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::parent(this), target, stream);
  }

  // .google.protobuf.Timestamp update_time = 4;
  if (this->has_update_time()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::update_time(this), target, stream);
  }

  // .google.protobuf.Any Metadata_cereal = 5;
  if (this->has_metadata_cereal()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::metadata_cereal(this), target, stream);
  }

  // .doodle.metadata_database.meta_type_value m_type = 6;
  if (this->has_m_type()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::m_type(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doodle.metadata_database)
  return target;
}

size_t metadata_database::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doodle.metadata_database)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string uuid_path = 2;
  if (this->uuid_path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_uuid_path());
  }

  // .google.protobuf.UInt64Value parent = 3;
  if (this->has_parent()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *parent_);
  }

  // .google.protobuf.Timestamp update_time = 4;
  if (this->has_update_time()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *update_time_);
  }

  // .google.protobuf.Any Metadata_cereal = 5;
  if (this->has_metadata_cereal()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *metadata_cereal_);
  }

  // .doodle.metadata_database.meta_type_value m_type = 6;
  if (this->has_m_type()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *m_type_);
  }

  // uint64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void metadata_database::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doodle.metadata_database)
  GOOGLE_DCHECK_NE(&from, this);
  const metadata_database* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<metadata_database>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doodle.metadata_database)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doodle.metadata_database)
    MergeFrom(*source);
  }
}

void metadata_database::MergeFrom(const metadata_database& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doodle.metadata_database)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uuid_path().size() > 0) {
    _internal_set_uuid_path(from._internal_uuid_path());
  }
  if (from.has_parent()) {
    _internal_mutable_parent()->PROTOBUF_NAMESPACE_ID::UInt64Value::MergeFrom(from._internal_parent());
  }
  if (from.has_update_time()) {
    _internal_mutable_update_time()->PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_update_time());
  }
  if (from.has_metadata_cereal()) {
    _internal_mutable_metadata_cereal()->PROTOBUF_NAMESPACE_ID::Any::MergeFrom(from._internal_metadata_cereal());
  }
  if (from.has_m_type()) {
    _internal_mutable_m_type()->::doodle::metadata_database_meta_type_value::MergeFrom(from._internal_m_type());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
}

void metadata_database::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doodle.metadata_database)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void metadata_database::CopyFrom(const metadata_database& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doodle.metadata_database)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool metadata_database::IsInitialized() const {
  return true;
}

void metadata_database::InternalSwap(metadata_database* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  uuid_path_.Swap(&other->uuid_path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(metadata_database, id_)
      + sizeof(metadata_database::id_)
      - PROTOBUF_FIELD_OFFSET(metadata_database, parent_)>(
          reinterpret_cast<char*>(&parent_),
          reinterpret_cast<char*>(&other->parent_));
}

::PROTOBUF_NAMESPACE_ID::Metadata metadata_database::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class metadata_database_filter::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::Timestamp& begin_time(const metadata_database_filter* msg);
  static const PROTOBUF_NAMESPACE_ID::Timestamp& end_time(const metadata_database_filter* msg);
  static const ::doodle::metadata_database_meta_type_value& m_type(const metadata_database_filter* msg);
  static const PROTOBUF_NAMESPACE_ID::UInt64Value& parent(const metadata_database_filter* msg);
};

const PROTOBUF_NAMESPACE_ID::Timestamp&
metadata_database_filter::_Internal::begin_time(const metadata_database_filter* msg) {
  return *msg->begin_time_;
}
const PROTOBUF_NAMESPACE_ID::Timestamp&
metadata_database_filter::_Internal::end_time(const metadata_database_filter* msg) {
  return *msg->end_time_;
}
const ::doodle::metadata_database_meta_type_value&
metadata_database_filter::_Internal::m_type(const metadata_database_filter* msg) {
  return *msg->m_type_;
}
const PROTOBUF_NAMESPACE_ID::UInt64Value&
metadata_database_filter::_Internal::parent(const metadata_database_filter* msg) {
  return *msg->parent_;
}
void metadata_database_filter::clear_begin_time() {
  if (GetArena() == nullptr && begin_time_ != nullptr) {
    delete begin_time_;
  }
  begin_time_ = nullptr;
}
void metadata_database_filter::clear_end_time() {
  if (GetArena() == nullptr && end_time_ != nullptr) {
    delete end_time_;
  }
  end_time_ = nullptr;
}
void metadata_database_filter::clear_parent() {
  if (GetArena() == nullptr && parent_ != nullptr) {
    delete parent_;
  }
  parent_ = nullptr;
}
metadata_database_filter::metadata_database_filter(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:doodle.metadata_database_filter)
}
metadata_database_filter::metadata_database_filter(const metadata_database_filter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_begin_time()) {
    begin_time_ = new PROTOBUF_NAMESPACE_ID::Timestamp(*from.begin_time_);
  } else {
    begin_time_ = nullptr;
  }
  if (from._internal_has_end_time()) {
    end_time_ = new PROTOBUF_NAMESPACE_ID::Timestamp(*from.end_time_);
  } else {
    end_time_ = nullptr;
  }
  if (from._internal_has_m_type()) {
    m_type_ = new ::doodle::metadata_database_meta_type_value(*from.m_type_);
  } else {
    m_type_ = nullptr;
  }
  if (from._internal_has_parent()) {
    parent_ = new PROTOBUF_NAMESPACE_ID::UInt64Value(*from.parent_);
  } else {
    parent_ = nullptr;
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:doodle.metadata_database_filter)
}

void metadata_database_filter::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&begin_time_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&begin_time_)) + sizeof(id_));
}

metadata_database_filter::~metadata_database_filter() {
  // @@protoc_insertion_point(destructor:doodle.metadata_database_filter)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void metadata_database_filter::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete begin_time_;
  if (this != internal_default_instance()) delete end_time_;
  if (this != internal_default_instance()) delete m_type_;
  if (this != internal_default_instance()) delete parent_;
}

void metadata_database_filter::ArenaDtor(void* object) {
  metadata_database_filter* _this = reinterpret_cast< metadata_database_filter* >(object);
  (void)_this;
}
void metadata_database_filter::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void metadata_database_filter::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void metadata_database_filter::Clear() {
// @@protoc_insertion_point(message_clear_start:doodle.metadata_database_filter)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && begin_time_ != nullptr) {
    delete begin_time_;
  }
  begin_time_ = nullptr;
  if (GetArena() == nullptr && end_time_ != nullptr) {
    delete end_time_;
  }
  end_time_ = nullptr;
  if (GetArena() == nullptr && m_type_ != nullptr) {
    delete m_type_;
  }
  m_type_ = nullptr;
  if (GetArena() == nullptr && parent_ != nullptr) {
    delete parent_;
  }
  parent_ = nullptr;
  id_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* metadata_database_filter::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp begin_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_begin_time(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp end_time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_end_time(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .doodle.metadata_database.meta_type_value m_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_m_type(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.UInt64Value parent = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_parent(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* metadata_database_filter::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:doodle.metadata_database_filter)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // .google.protobuf.Timestamp begin_time = 2;
  if (this->has_begin_time()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::begin_time(this), target, stream);
  }

  // .google.protobuf.Timestamp end_time = 3;
  if (this->has_end_time()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::end_time(this), target, stream);
  }

  // .doodle.metadata_database.meta_type_value m_type = 4;
  if (this->has_m_type()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::m_type(this), target, stream);
  }

  // .google.protobuf.UInt64Value parent = 5;
  if (this->has_parent()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::parent(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doodle.metadata_database_filter)
  return target;
}

size_t metadata_database_filter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doodle.metadata_database_filter)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp begin_time = 2;
  if (this->has_begin_time()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *begin_time_);
  }

  // .google.protobuf.Timestamp end_time = 3;
  if (this->has_end_time()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *end_time_);
  }

  // .doodle.metadata_database.meta_type_value m_type = 4;
  if (this->has_m_type()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *m_type_);
  }

  // .google.protobuf.UInt64Value parent = 5;
  if (this->has_parent()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *parent_);
  }

  // uint64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void metadata_database_filter::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doodle.metadata_database_filter)
  GOOGLE_DCHECK_NE(&from, this);
  const metadata_database_filter* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<metadata_database_filter>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doodle.metadata_database_filter)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doodle.metadata_database_filter)
    MergeFrom(*source);
  }
}

void metadata_database_filter::MergeFrom(const metadata_database_filter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doodle.metadata_database_filter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_begin_time()) {
    _internal_mutable_begin_time()->PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_begin_time());
  }
  if (from.has_end_time()) {
    _internal_mutable_end_time()->PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_end_time());
  }
  if (from.has_m_type()) {
    _internal_mutable_m_type()->::doodle::metadata_database_meta_type_value::MergeFrom(from._internal_m_type());
  }
  if (from.has_parent()) {
    _internal_mutable_parent()->PROTOBUF_NAMESPACE_ID::UInt64Value::MergeFrom(from._internal_parent());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
}

void metadata_database_filter::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doodle.metadata_database_filter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void metadata_database_filter::CopyFrom(const metadata_database_filter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doodle.metadata_database_filter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool metadata_database_filter::IsInitialized() const {
  return true;
}

void metadata_database_filter::InternalSwap(metadata_database_filter* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(metadata_database_filter, id_)
      + sizeof(metadata_database_filter::id_)
      - PROTOBUF_FIELD_OFFSET(metadata_database_filter, begin_time_)>(
          reinterpret_cast<char*>(&begin_time_),
          reinterpret_cast<char*>(&other->begin_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata metadata_database_filter::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace doodle
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::doodle::metadata_database_meta_type_value* Arena::CreateMaybeMessage< ::doodle::metadata_database_meta_type_value >(Arena* arena) {
  return Arena::CreateMessageInternal< ::doodle::metadata_database_meta_type_value >(arena);
}
template<> PROTOBUF_NOINLINE ::doodle::metadata_database* Arena::CreateMaybeMessage< ::doodle::metadata_database >(Arena* arena) {
  return Arena::CreateMessageInternal< ::doodle::metadata_database >(arena);
}
template<> PROTOBUF_NOINLINE ::doodle::metadata_database_filter* Arena::CreateMaybeMessage< ::doodle::metadata_database_filter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::doodle::metadata_database_filter >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
