// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetadataServer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MetadataServer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MetadataServer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include <google/protobuf/any.pb.h>
#include <google/protobuf/wrappers.pb.h>
#include "UserMessage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MetadataServer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MetadataServer_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MetadataServer_2eproto;
namespace doodle {
class DataDb;
class DataDbDefaultTypeInternal;
extern DataDbDefaultTypeInternal _DataDb_default_instance_;
class DataDb_Filter;
class DataDb_FilterDefaultTypeInternal;
extern DataDb_FilterDefaultTypeInternal _DataDb_Filter_default_instance_;
class DataDb_meta_type_value;
class DataDb_meta_type_valueDefaultTypeInternal;
extern DataDb_meta_type_valueDefaultTypeInternal _DataDb_meta_type_value_default_instance_;
}  // namespace doodle
PROTOBUF_NAMESPACE_OPEN
template<> ::doodle::DataDb* Arena::CreateMaybeMessage<::doodle::DataDb>(Arena*);
template<> ::doodle::DataDb_Filter* Arena::CreateMaybeMessage<::doodle::DataDb_Filter>(Arena*);
template<> ::doodle::DataDb_meta_type_value* Arena::CreateMaybeMessage<::doodle::DataDb_meta_type_value>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace doodle {

enum DataDb_meta_type : int {
  DataDb_meta_type_unknown_file = 0,
  DataDb_meta_type_project_root = 1,
  DataDb_meta_type_file = 2,
  DataDb_meta_type_folder = 3,
  DataDb_meta_type_derive_file = 4,
  DataDb_meta_type_animation_lib_root = 5,
  DataDb_meta_type_DataDb_meta_type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DataDb_meta_type_DataDb_meta_type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool DataDb_meta_type_IsValid(int value);
constexpr DataDb_meta_type DataDb_meta_type_meta_type_MIN = DataDb_meta_type_unknown_file;
constexpr DataDb_meta_type DataDb_meta_type_meta_type_MAX = DataDb_meta_type_animation_lib_root;
constexpr int DataDb_meta_type_meta_type_ARRAYSIZE = DataDb_meta_type_meta_type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataDb_meta_type_descriptor();
template<typename T>
inline const std::string& DataDb_meta_type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DataDb_meta_type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DataDb_meta_type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DataDb_meta_type_descriptor(), enum_t_value);
}
inline bool DataDb_meta_type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DataDb_meta_type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DataDb_meta_type>(
    DataDb_meta_type_descriptor(), name, value);
}
// ===================================================================

class DataDb_meta_type_value PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:doodle.DataDb.meta_type_value) */ {
 public:
  inline DataDb_meta_type_value() : DataDb_meta_type_value(nullptr) {}
  virtual ~DataDb_meta_type_value();

  DataDb_meta_type_value(const DataDb_meta_type_value& from);
  DataDb_meta_type_value(DataDb_meta_type_value&& from) noexcept
    : DataDb_meta_type_value() {
    *this = ::std::move(from);
  }

  inline DataDb_meta_type_value& operator=(const DataDb_meta_type_value& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataDb_meta_type_value& operator=(DataDb_meta_type_value&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataDb_meta_type_value& default_instance();

  static inline const DataDb_meta_type_value* internal_default_instance() {
    return reinterpret_cast<const DataDb_meta_type_value*>(
               &_DataDb_meta_type_value_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DataDb_meta_type_value& a, DataDb_meta_type_value& b) {
    a.Swap(&b);
  }
  inline void Swap(DataDb_meta_type_value* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataDb_meta_type_value* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataDb_meta_type_value* New() const final {
    return CreateMaybeMessage<DataDb_meta_type_value>(nullptr);
  }

  DataDb_meta_type_value* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataDb_meta_type_value>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataDb_meta_type_value& from);
  void MergeFrom(const DataDb_meta_type_value& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataDb_meta_type_value* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "doodle.DataDb.meta_type_value";
  }
  protected:
  explicit DataDb_meta_type_value(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MetadataServer_2eproto);
    return ::descriptor_table_MetadataServer_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // .doodle.DataDb.meta_type value = 1;
  void clear_value();
  ::doodle::DataDb_meta_type value() const;
  void set_value(::doodle::DataDb_meta_type value);
  private:
  ::doodle::DataDb_meta_type _internal_value() const;
  void _internal_set_value(::doodle::DataDb_meta_type value);
  public:

  // @@protoc_insertion_point(class_scope:doodle.DataDb.meta_type_value)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MetadataServer_2eproto;
};
// -------------------------------------------------------------------

class DataDb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:doodle.DataDb) */ {
 public:
  inline DataDb() : DataDb(nullptr) {}
  virtual ~DataDb();

  DataDb(const DataDb& from);
  DataDb(DataDb&& from) noexcept
    : DataDb() {
    *this = ::std::move(from);
  }

  inline DataDb& operator=(const DataDb& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataDb& operator=(DataDb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataDb& default_instance();

  static inline const DataDb* internal_default_instance() {
    return reinterpret_cast<const DataDb*>(
               &_DataDb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DataDb& a, DataDb& b) {
    a.Swap(&b);
  }
  inline void Swap(DataDb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataDb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataDb* New() const final {
    return CreateMaybeMessage<DataDb>(nullptr);
  }

  DataDb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataDb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataDb& from);
  void MergeFrom(const DataDb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataDb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "doodle.DataDb";
  }
  protected:
  explicit DataDb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MetadataServer_2eproto);
    return ::descriptor_table_MetadataServer_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef DataDb_meta_type_value meta_type_value;

  typedef DataDb_meta_type meta_type;
  static constexpr meta_type unknown_file =
    DataDb_meta_type_unknown_file;
  static constexpr meta_type project_root =
    DataDb_meta_type_project_root;
  static constexpr meta_type file =
    DataDb_meta_type_file;
  static constexpr meta_type folder =
    DataDb_meta_type_folder;
  static constexpr meta_type derive_file =
    DataDb_meta_type_derive_file;
  static constexpr meta_type animation_lib_root =
    DataDb_meta_type_animation_lib_root;
  static inline bool meta_type_IsValid(int value) {
    return DataDb_meta_type_IsValid(value);
  }
  static constexpr meta_type meta_type_MIN =
    DataDb_meta_type_meta_type_MIN;
  static constexpr meta_type meta_type_MAX =
    DataDb_meta_type_meta_type_MAX;
  static constexpr int meta_type_ARRAYSIZE =
    DataDb_meta_type_meta_type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  meta_type_descriptor() {
    return DataDb_meta_type_descriptor();
  }
  template<typename T>
  static inline const std::string& meta_type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, meta_type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function meta_type_Name.");
    return DataDb_meta_type_Name(enum_t_value);
  }
  static inline bool meta_type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      meta_type* value) {
    return DataDb_meta_type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kUuidPathFieldNumber = 2,
    kParentFieldNumber = 3,
    kUpdateTimeFieldNumber = 4,
    kMetadataCerealFieldNumber = 5,
    kMTypeFieldNumber = 6,
    kIdFieldNumber = 1,
  };
  // string uuidPath = 2;
  void clear_uuidpath();
  const std::string& uuidpath() const;
  void set_uuidpath(const std::string& value);
  void set_uuidpath(std::string&& value);
  void set_uuidpath(const char* value);
  void set_uuidpath(const char* value, size_t size);
  std::string* mutable_uuidpath();
  std::string* release_uuidpath();
  void set_allocated_uuidpath(std::string* uuidpath);
  private:
  const std::string& _internal_uuidpath() const;
  void _internal_set_uuidpath(const std::string& value);
  std::string* _internal_mutable_uuidpath();
  public:

  // .google.protobuf.UInt64Value parent = 3;
  bool has_parent() const;
  private:
  bool _internal_has_parent() const;
  public:
  void clear_parent();
  const PROTOBUF_NAMESPACE_ID::UInt64Value& parent() const;
  PROTOBUF_NAMESPACE_ID::UInt64Value* release_parent();
  PROTOBUF_NAMESPACE_ID::UInt64Value* mutable_parent();
  void set_allocated_parent(PROTOBUF_NAMESPACE_ID::UInt64Value* parent);
  private:
  const PROTOBUF_NAMESPACE_ID::UInt64Value& _internal_parent() const;
  PROTOBUF_NAMESPACE_ID::UInt64Value* _internal_mutable_parent();
  public:
  void unsafe_arena_set_allocated_parent(
      PROTOBUF_NAMESPACE_ID::UInt64Value* parent);
  PROTOBUF_NAMESPACE_ID::UInt64Value* unsafe_arena_release_parent();

  // .google.protobuf.Timestamp update_time = 4;
  bool has_update_time() const;
  private:
  bool _internal_has_update_time() const;
  public:
  void clear_update_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& update_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_update_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_update_time();
  void set_allocated_update_time(PROTOBUF_NAMESPACE_ID::Timestamp* update_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_update_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_update_time();
  public:
  void unsafe_arena_set_allocated_update_time(
      PROTOBUF_NAMESPACE_ID::Timestamp* update_time);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_update_time();

  // .google.protobuf.Any Metadata_cereal = 5;
  bool has_metadata_cereal() const;
  private:
  bool _internal_has_metadata_cereal() const;
  public:
  void clear_metadata_cereal();
  const PROTOBUF_NAMESPACE_ID::Any& metadata_cereal() const;
  PROTOBUF_NAMESPACE_ID::Any* release_metadata_cereal();
  PROTOBUF_NAMESPACE_ID::Any* mutable_metadata_cereal();
  void set_allocated_metadata_cereal(PROTOBUF_NAMESPACE_ID::Any* metadata_cereal);
  private:
  const PROTOBUF_NAMESPACE_ID::Any& _internal_metadata_cereal() const;
  PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_metadata_cereal();
  public:
  void unsafe_arena_set_allocated_metadata_cereal(
      PROTOBUF_NAMESPACE_ID::Any* metadata_cereal);
  PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_metadata_cereal();

  // .doodle.DataDb.meta_type_value m_type = 6;
  bool has_m_type() const;
  private:
  bool _internal_has_m_type() const;
  public:
  void clear_m_type();
  const ::doodle::DataDb_meta_type_value& m_type() const;
  ::doodle::DataDb_meta_type_value* release_m_type();
  ::doodle::DataDb_meta_type_value* mutable_m_type();
  void set_allocated_m_type(::doodle::DataDb_meta_type_value* m_type);
  private:
  const ::doodle::DataDb_meta_type_value& _internal_m_type() const;
  ::doodle::DataDb_meta_type_value* _internal_mutable_m_type();
  public:
  void unsafe_arena_set_allocated_m_type(
      ::doodle::DataDb_meta_type_value* m_type);
  ::doodle::DataDb_meta_type_value* unsafe_arena_release_m_type();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:doodle.DataDb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuidpath_;
  PROTOBUF_NAMESPACE_ID::UInt64Value* parent_;
  PROTOBUF_NAMESPACE_ID::Timestamp* update_time_;
  PROTOBUF_NAMESPACE_ID::Any* metadata_cereal_;
  ::doodle::DataDb_meta_type_value* m_type_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MetadataServer_2eproto;
};
// -------------------------------------------------------------------

class DataDb_Filter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:doodle.DataDb_Filter) */ {
 public:
  inline DataDb_Filter() : DataDb_Filter(nullptr) {}
  virtual ~DataDb_Filter();

  DataDb_Filter(const DataDb_Filter& from);
  DataDb_Filter(DataDb_Filter&& from) noexcept
    : DataDb_Filter() {
    *this = ::std::move(from);
  }

  inline DataDb_Filter& operator=(const DataDb_Filter& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataDb_Filter& operator=(DataDb_Filter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataDb_Filter& default_instance();

  static inline const DataDb_Filter* internal_default_instance() {
    return reinterpret_cast<const DataDb_Filter*>(
               &_DataDb_Filter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DataDb_Filter& a, DataDb_Filter& b) {
    a.Swap(&b);
  }
  inline void Swap(DataDb_Filter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataDb_Filter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataDb_Filter* New() const final {
    return CreateMaybeMessage<DataDb_Filter>(nullptr);
  }

  DataDb_Filter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataDb_Filter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataDb_Filter& from);
  void MergeFrom(const DataDb_Filter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataDb_Filter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "doodle.DataDb_Filter";
  }
  protected:
  explicit DataDb_Filter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MetadataServer_2eproto);
    return ::descriptor_table_MetadataServer_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBeginTimeFieldNumber = 2,
    kEndTimeFieldNumber = 3,
    kMTypeFieldNumber = 4,
    kParentFieldNumber = 5,
    kIdFieldNumber = 1,
  };
  // .google.protobuf.Timestamp begin_time = 2;
  bool has_begin_time() const;
  private:
  bool _internal_has_begin_time() const;
  public:
  void clear_begin_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& begin_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_begin_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_begin_time();
  void set_allocated_begin_time(PROTOBUF_NAMESPACE_ID::Timestamp* begin_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_begin_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_begin_time();
  public:
  void unsafe_arena_set_allocated_begin_time(
      PROTOBUF_NAMESPACE_ID::Timestamp* begin_time);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_begin_time();

  // .google.protobuf.Timestamp end_time = 3;
  bool has_end_time() const;
  private:
  bool _internal_has_end_time() const;
  public:
  void clear_end_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& end_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_end_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_end_time();
  void set_allocated_end_time(PROTOBUF_NAMESPACE_ID::Timestamp* end_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_end_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_end_time();
  public:
  void unsafe_arena_set_allocated_end_time(
      PROTOBUF_NAMESPACE_ID::Timestamp* end_time);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_end_time();

  // .doodle.DataDb.meta_type_value m_type = 4;
  bool has_m_type() const;
  private:
  bool _internal_has_m_type() const;
  public:
  void clear_m_type();
  const ::doodle::DataDb_meta_type_value& m_type() const;
  ::doodle::DataDb_meta_type_value* release_m_type();
  ::doodle::DataDb_meta_type_value* mutable_m_type();
  void set_allocated_m_type(::doodle::DataDb_meta_type_value* m_type);
  private:
  const ::doodle::DataDb_meta_type_value& _internal_m_type() const;
  ::doodle::DataDb_meta_type_value* _internal_mutable_m_type();
  public:
  void unsafe_arena_set_allocated_m_type(
      ::doodle::DataDb_meta_type_value* m_type);
  ::doodle::DataDb_meta_type_value* unsafe_arena_release_m_type();

  // .google.protobuf.UInt64Value parent = 5;
  bool has_parent() const;
  private:
  bool _internal_has_parent() const;
  public:
  void clear_parent();
  const PROTOBUF_NAMESPACE_ID::UInt64Value& parent() const;
  PROTOBUF_NAMESPACE_ID::UInt64Value* release_parent();
  PROTOBUF_NAMESPACE_ID::UInt64Value* mutable_parent();
  void set_allocated_parent(PROTOBUF_NAMESPACE_ID::UInt64Value* parent);
  private:
  const PROTOBUF_NAMESPACE_ID::UInt64Value& _internal_parent() const;
  PROTOBUF_NAMESPACE_ID::UInt64Value* _internal_mutable_parent();
  public:
  void unsafe_arena_set_allocated_parent(
      PROTOBUF_NAMESPACE_ID::UInt64Value* parent);
  PROTOBUF_NAMESPACE_ID::UInt64Value* unsafe_arena_release_parent();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:doodle.DataDb_Filter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  PROTOBUF_NAMESPACE_ID::Timestamp* begin_time_;
  PROTOBUF_NAMESPACE_ID::Timestamp* end_time_;
  ::doodle::DataDb_meta_type_value* m_type_;
  PROTOBUF_NAMESPACE_ID::UInt64Value* parent_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MetadataServer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DataDb_meta_type_value

// .doodle.DataDb.meta_type value = 1;
inline void DataDb_meta_type_value::clear_value() {
  value_ = 0;
}
inline ::doodle::DataDb_meta_type DataDb_meta_type_value::_internal_value() const {
  return static_cast< ::doodle::DataDb_meta_type >(value_);
}
inline ::doodle::DataDb_meta_type DataDb_meta_type_value::value() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.meta_type_value.value)
  return _internal_value();
}
inline void DataDb_meta_type_value::_internal_set_value(::doodle::DataDb_meta_type value) {
  
  value_ = value;
}
inline void DataDb_meta_type_value::set_value(::doodle::DataDb_meta_type value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:doodle.DataDb.meta_type_value.value)
}

// -------------------------------------------------------------------

// DataDb

// uint64 id = 1;
inline void DataDb::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DataDb::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DataDb::id() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.id)
  return _internal_id();
}
inline void DataDb::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void DataDb::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:doodle.DataDb.id)
}

// string uuidPath = 2;
inline void DataDb::clear_uuidpath() {
  uuidpath_.ClearToEmpty();
}
inline const std::string& DataDb::uuidpath() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.uuidPath)
  return _internal_uuidpath();
}
inline void DataDb::set_uuidpath(const std::string& value) {
  _internal_set_uuidpath(value);
  // @@protoc_insertion_point(field_set:doodle.DataDb.uuidPath)
}
inline std::string* DataDb::mutable_uuidpath() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb.uuidPath)
  return _internal_mutable_uuidpath();
}
inline const std::string& DataDb::_internal_uuidpath() const {
  return uuidpath_.Get();
}
inline void DataDb::_internal_set_uuidpath(const std::string& value) {
  
  uuidpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void DataDb::set_uuidpath(std::string&& value) {
  
  uuidpath_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:doodle.DataDb.uuidPath)
}
inline void DataDb::set_uuidpath(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuidpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:doodle.DataDb.uuidPath)
}
inline void DataDb::set_uuidpath(const char* value,
    size_t size) {
  
  uuidpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:doodle.DataDb.uuidPath)
}
inline std::string* DataDb::_internal_mutable_uuidpath() {
  
  return uuidpath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* DataDb::release_uuidpath() {
  // @@protoc_insertion_point(field_release:doodle.DataDb.uuidPath)
  return uuidpath_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void DataDb::set_allocated_uuidpath(std::string* uuidpath) {
  if (uuidpath != nullptr) {
    
  } else {
    
  }
  uuidpath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuidpath,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb.uuidPath)
}

// .google.protobuf.UInt64Value parent = 3;
inline bool DataDb::_internal_has_parent() const {
  return this != internal_default_instance() && parent_ != nullptr;
}
inline bool DataDb::has_parent() const {
  return _internal_has_parent();
}
inline const PROTOBUF_NAMESPACE_ID::UInt64Value& DataDb::_internal_parent() const {
  const PROTOBUF_NAMESPACE_ID::UInt64Value* p = parent_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::UInt64Value&>(
      PROTOBUF_NAMESPACE_ID::_UInt64Value_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::UInt64Value& DataDb::parent() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.parent)
  return _internal_parent();
}
inline void DataDb::unsafe_arena_set_allocated_parent(
    PROTOBUF_NAMESPACE_ID::UInt64Value* parent) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parent_);
  }
  parent_ = parent;
  if (parent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb.parent)
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb::release_parent() {
  
  PROTOBUF_NAMESPACE_ID::UInt64Value* temp = parent_;
  parent_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb::unsafe_arena_release_parent() {
  // @@protoc_insertion_point(field_release:doodle.DataDb.parent)
  
  PROTOBUF_NAMESPACE_ID::UInt64Value* temp = parent_;
  parent_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb::_internal_mutable_parent() {
  
  if (parent_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::UInt64Value>(GetArena());
    parent_ = p;
  }
  return parent_;
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb::mutable_parent() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb.parent)
  return _internal_mutable_parent();
}
inline void DataDb::set_allocated_parent(PROTOBUF_NAMESPACE_ID::UInt64Value* parent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(parent_);
  }
  if (parent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parent)->GetArena();
    if (message_arena != submessage_arena) {
      parent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, parent, submessage_arena);
    }
    
  } else {
    
  }
  parent_ = parent;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb.parent)
}

// .google.protobuf.Timestamp update_time = 4;
inline bool DataDb::_internal_has_update_time() const {
  return this != internal_default_instance() && update_time_ != nullptr;
}
inline bool DataDb::has_update_time() const {
  return _internal_has_update_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& DataDb::_internal_update_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = update_time_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp&>(
      PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& DataDb::update_time() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.update_time)
  return _internal_update_time();
}
inline void DataDb::unsafe_arena_set_allocated_update_time(
    PROTOBUF_NAMESPACE_ID::Timestamp* update_time) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(update_time_);
  }
  update_time_ = update_time;
  if (update_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb.update_time)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb::release_update_time() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = update_time_;
  update_time_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb::unsafe_arena_release_update_time() {
  // @@protoc_insertion_point(field_release:doodle.DataDb.update_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = update_time_;
  update_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb::_internal_mutable_update_time() {
  
  if (update_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    update_time_ = p;
  }
  return update_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb::mutable_update_time() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb.update_time)
  return _internal_mutable_update_time();
}
inline void DataDb::set_allocated_update_time(PROTOBUF_NAMESPACE_ID::Timestamp* update_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(update_time_);
  }
  if (update_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(update_time)->GetArena();
    if (message_arena != submessage_arena) {
      update_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update_time, submessage_arena);
    }
    
  } else {
    
  }
  update_time_ = update_time;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb.update_time)
}

// .google.protobuf.Any Metadata_cereal = 5;
inline bool DataDb::_internal_has_metadata_cereal() const {
  return this != internal_default_instance() && metadata_cereal_ != nullptr;
}
inline bool DataDb::has_metadata_cereal() const {
  return _internal_has_metadata_cereal();
}
inline const PROTOBUF_NAMESPACE_ID::Any& DataDb::_internal_metadata_cereal() const {
  const PROTOBUF_NAMESPACE_ID::Any* p = metadata_cereal_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Any&>(
      PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Any& DataDb::metadata_cereal() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.Metadata_cereal)
  return _internal_metadata_cereal();
}
inline void DataDb::unsafe_arena_set_allocated_metadata_cereal(
    PROTOBUF_NAMESPACE_ID::Any* metadata_cereal) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(metadata_cereal_);
  }
  metadata_cereal_ = metadata_cereal;
  if (metadata_cereal) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb.Metadata_cereal)
}
inline PROTOBUF_NAMESPACE_ID::Any* DataDb::release_metadata_cereal() {
  
  PROTOBUF_NAMESPACE_ID::Any* temp = metadata_cereal_;
  metadata_cereal_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Any* DataDb::unsafe_arena_release_metadata_cereal() {
  // @@protoc_insertion_point(field_release:doodle.DataDb.Metadata_cereal)
  
  PROTOBUF_NAMESPACE_ID::Any* temp = metadata_cereal_;
  metadata_cereal_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Any* DataDb::_internal_mutable_metadata_cereal() {
  
  if (metadata_cereal_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Any>(GetArena());
    metadata_cereal_ = p;
  }
  return metadata_cereal_;
}
inline PROTOBUF_NAMESPACE_ID::Any* DataDb::mutable_metadata_cereal() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb.Metadata_cereal)
  return _internal_mutable_metadata_cereal();
}
inline void DataDb::set_allocated_metadata_cereal(PROTOBUF_NAMESPACE_ID::Any* metadata_cereal) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(metadata_cereal_);
  }
  if (metadata_cereal) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(metadata_cereal)->GetArena();
    if (message_arena != submessage_arena) {
      metadata_cereal = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, metadata_cereal, submessage_arena);
    }
    
  } else {
    
  }
  metadata_cereal_ = metadata_cereal;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb.Metadata_cereal)
}

// .doodle.DataDb.meta_type_value m_type = 6;
inline bool DataDb::_internal_has_m_type() const {
  return this != internal_default_instance() && m_type_ != nullptr;
}
inline bool DataDb::has_m_type() const {
  return _internal_has_m_type();
}
inline void DataDb::clear_m_type() {
  if (GetArena() == nullptr && m_type_ != nullptr) {
    delete m_type_;
  }
  m_type_ = nullptr;
}
inline const ::doodle::DataDb_meta_type_value& DataDb::_internal_m_type() const {
  const ::doodle::DataDb_meta_type_value* p = m_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::doodle::DataDb_meta_type_value&>(
      ::doodle::_DataDb_meta_type_value_default_instance_);
}
inline const ::doodle::DataDb_meta_type_value& DataDb::m_type() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb.m_type)
  return _internal_m_type();
}
inline void DataDb::unsafe_arena_set_allocated_m_type(
    ::doodle::DataDb_meta_type_value* m_type) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(m_type_);
  }
  m_type_ = m_type;
  if (m_type) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb.m_type)
}
inline ::doodle::DataDb_meta_type_value* DataDb::release_m_type() {
  
  ::doodle::DataDb_meta_type_value* temp = m_type_;
  m_type_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::doodle::DataDb_meta_type_value* DataDb::unsafe_arena_release_m_type() {
  // @@protoc_insertion_point(field_release:doodle.DataDb.m_type)
  
  ::doodle::DataDb_meta_type_value* temp = m_type_;
  m_type_ = nullptr;
  return temp;
}
inline ::doodle::DataDb_meta_type_value* DataDb::_internal_mutable_m_type() {
  
  if (m_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::doodle::DataDb_meta_type_value>(GetArena());
    m_type_ = p;
  }
  return m_type_;
}
inline ::doodle::DataDb_meta_type_value* DataDb::mutable_m_type() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb.m_type)
  return _internal_mutable_m_type();
}
inline void DataDb::set_allocated_m_type(::doodle::DataDb_meta_type_value* m_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete m_type_;
  }
  if (m_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(m_type);
    if (message_arena != submessage_arena) {
      m_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_type, submessage_arena);
    }
    
  } else {
    
  }
  m_type_ = m_type;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb.m_type)
}

// -------------------------------------------------------------------

// DataDb_Filter

// uint64 id = 1;
inline void DataDb_Filter::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DataDb_Filter::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DataDb_Filter::id() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb_Filter.id)
  return _internal_id();
}
inline void DataDb_Filter::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void DataDb_Filter::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:doodle.DataDb_Filter.id)
}

// .google.protobuf.Timestamp begin_time = 2;
inline bool DataDb_Filter::_internal_has_begin_time() const {
  return this != internal_default_instance() && begin_time_ != nullptr;
}
inline bool DataDb_Filter::has_begin_time() const {
  return _internal_has_begin_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& DataDb_Filter::_internal_begin_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = begin_time_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp&>(
      PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& DataDb_Filter::begin_time() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb_Filter.begin_time)
  return _internal_begin_time();
}
inline void DataDb_Filter::unsafe_arena_set_allocated_begin_time(
    PROTOBUF_NAMESPACE_ID::Timestamp* begin_time) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(begin_time_);
  }
  begin_time_ = begin_time;
  if (begin_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb_Filter.begin_time)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::release_begin_time() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = begin_time_;
  begin_time_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::unsafe_arena_release_begin_time() {
  // @@protoc_insertion_point(field_release:doodle.DataDb_Filter.begin_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = begin_time_;
  begin_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::_internal_mutable_begin_time() {
  
  if (begin_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    begin_time_ = p;
  }
  return begin_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::mutable_begin_time() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb_Filter.begin_time)
  return _internal_mutable_begin_time();
}
inline void DataDb_Filter::set_allocated_begin_time(PROTOBUF_NAMESPACE_ID::Timestamp* begin_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(begin_time_);
  }
  if (begin_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(begin_time)->GetArena();
    if (message_arena != submessage_arena) {
      begin_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, begin_time, submessage_arena);
    }
    
  } else {
    
  }
  begin_time_ = begin_time;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb_Filter.begin_time)
}

// .google.protobuf.Timestamp end_time = 3;
inline bool DataDb_Filter::_internal_has_end_time() const {
  return this != internal_default_instance() && end_time_ != nullptr;
}
inline bool DataDb_Filter::has_end_time() const {
  return _internal_has_end_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& DataDb_Filter::_internal_end_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = end_time_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp&>(
      PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& DataDb_Filter::end_time() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb_Filter.end_time)
  return _internal_end_time();
}
inline void DataDb_Filter::unsafe_arena_set_allocated_end_time(
    PROTOBUF_NAMESPACE_ID::Timestamp* end_time) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(end_time_);
  }
  end_time_ = end_time;
  if (end_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb_Filter.end_time)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::release_end_time() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = end_time_;
  end_time_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::unsafe_arena_release_end_time() {
  // @@protoc_insertion_point(field_release:doodle.DataDb_Filter.end_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = end_time_;
  end_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::_internal_mutable_end_time() {
  
  if (end_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    end_time_ = p;
  }
  return end_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* DataDb_Filter::mutable_end_time() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb_Filter.end_time)
  return _internal_mutable_end_time();
}
inline void DataDb_Filter::set_allocated_end_time(PROTOBUF_NAMESPACE_ID::Timestamp* end_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(end_time_);
  }
  if (end_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(end_time)->GetArena();
    if (message_arena != submessage_arena) {
      end_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, end_time, submessage_arena);
    }
    
  } else {
    
  }
  end_time_ = end_time;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb_Filter.end_time)
}

// .doodle.DataDb.meta_type_value m_type = 4;
inline bool DataDb_Filter::_internal_has_m_type() const {
  return this != internal_default_instance() && m_type_ != nullptr;
}
inline bool DataDb_Filter::has_m_type() const {
  return _internal_has_m_type();
}
inline void DataDb_Filter::clear_m_type() {
  if (GetArena() == nullptr && m_type_ != nullptr) {
    delete m_type_;
  }
  m_type_ = nullptr;
}
inline const ::doodle::DataDb_meta_type_value& DataDb_Filter::_internal_m_type() const {
  const ::doodle::DataDb_meta_type_value* p = m_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::doodle::DataDb_meta_type_value&>(
      ::doodle::_DataDb_meta_type_value_default_instance_);
}
inline const ::doodle::DataDb_meta_type_value& DataDb_Filter::m_type() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb_Filter.m_type)
  return _internal_m_type();
}
inline void DataDb_Filter::unsafe_arena_set_allocated_m_type(
    ::doodle::DataDb_meta_type_value* m_type) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(m_type_);
  }
  m_type_ = m_type;
  if (m_type) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb_Filter.m_type)
}
inline ::doodle::DataDb_meta_type_value* DataDb_Filter::release_m_type() {
  
  ::doodle::DataDb_meta_type_value* temp = m_type_;
  m_type_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::doodle::DataDb_meta_type_value* DataDb_Filter::unsafe_arena_release_m_type() {
  // @@protoc_insertion_point(field_release:doodle.DataDb_Filter.m_type)
  
  ::doodle::DataDb_meta_type_value* temp = m_type_;
  m_type_ = nullptr;
  return temp;
}
inline ::doodle::DataDb_meta_type_value* DataDb_Filter::_internal_mutable_m_type() {
  
  if (m_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::doodle::DataDb_meta_type_value>(GetArena());
    m_type_ = p;
  }
  return m_type_;
}
inline ::doodle::DataDb_meta_type_value* DataDb_Filter::mutable_m_type() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb_Filter.m_type)
  return _internal_mutable_m_type();
}
inline void DataDb_Filter::set_allocated_m_type(::doodle::DataDb_meta_type_value* m_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete m_type_;
  }
  if (m_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(m_type);
    if (message_arena != submessage_arena) {
      m_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_type, submessage_arena);
    }
    
  } else {
    
  }
  m_type_ = m_type;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb_Filter.m_type)
}

// .google.protobuf.UInt64Value parent = 5;
inline bool DataDb_Filter::_internal_has_parent() const {
  return this != internal_default_instance() && parent_ != nullptr;
}
inline bool DataDb_Filter::has_parent() const {
  return _internal_has_parent();
}
inline const PROTOBUF_NAMESPACE_ID::UInt64Value& DataDb_Filter::_internal_parent() const {
  const PROTOBUF_NAMESPACE_ID::UInt64Value* p = parent_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::UInt64Value&>(
      PROTOBUF_NAMESPACE_ID::_UInt64Value_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::UInt64Value& DataDb_Filter::parent() const {
  // @@protoc_insertion_point(field_get:doodle.DataDb_Filter.parent)
  return _internal_parent();
}
inline void DataDb_Filter::unsafe_arena_set_allocated_parent(
    PROTOBUF_NAMESPACE_ID::UInt64Value* parent) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parent_);
  }
  parent_ = parent;
  if (parent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:doodle.DataDb_Filter.parent)
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb_Filter::release_parent() {
  
  PROTOBUF_NAMESPACE_ID::UInt64Value* temp = parent_;
  parent_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb_Filter::unsafe_arena_release_parent() {
  // @@protoc_insertion_point(field_release:doodle.DataDb_Filter.parent)
  
  PROTOBUF_NAMESPACE_ID::UInt64Value* temp = parent_;
  parent_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb_Filter::_internal_mutable_parent() {
  
  if (parent_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::UInt64Value>(GetArena());
    parent_ = p;
  }
  return parent_;
}
inline PROTOBUF_NAMESPACE_ID::UInt64Value* DataDb_Filter::mutable_parent() {
  // @@protoc_insertion_point(field_mutable:doodle.DataDb_Filter.parent)
  return _internal_mutable_parent();
}
inline void DataDb_Filter::set_allocated_parent(PROTOBUF_NAMESPACE_ID::UInt64Value* parent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(parent_);
  }
  if (parent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parent)->GetArena();
    if (message_arena != submessage_arena) {
      parent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, parent, submessage_arena);
    }
    
  } else {
    
  }
  parent_ = parent;
  // @@protoc_insertion_point(field_set_allocated:doodle.DataDb_Filter.parent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace doodle

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::doodle::DataDb_meta_type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::doodle::DataDb_meta_type>() {
  return ::doodle::DataDb_meta_type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MetadataServer_2eproto
