set(
        DOODLELIB_HEADER
        DoodleApp.h
        DoodleLib.h
        DoodleLib_fwd.h
        core/CoreSet.h
        core/CoreSql.h
        core/MetadataSet.h
        core/Name.h
        core/ToolsSetting.h
        core/Ue4Setting.h
        Exception/Exception.h
        FileSys/FileSystem.h
        FileWarp/ImageSequence.h
        FileWarp/MayaFile.h
        FileWarp/Ue4Project.h
        FileWarp/VideoSequence.h
        libWarp/BoostUuidWarp.h
        Logger/Logger.h
        Logger/LoggerTemplate.h
        mainWidght/mainWindows.h
        mainWidght/systemTray.h
        Metadata/Assets.h
        Metadata/AssetsFile.h
        Metadata/Episodes.h
        Metadata/Metadata.h
        Metadata/MetadataFactory.h
        Metadata/MetadataWidget.h
        Metadata/Project.h
        Metadata/Shot.h
        Metadata/Label/LabelNode.h
        Metadata/Model/AssstsTree.h
        Metadata/View/ShotListWidget.h
        PinYin/convert.h
        ScreenshotWidght/ScreenshotAction.h
        ScreenshotWidght/ScreenshotWidght.h
        SettingWidght/settingWidget.h
        threadPool/LongTerm.h
        threadPool/ThreadPool.h
        toolkit/MessageAndProgress.h
        toolkit/toolkit.h
        libWarp/WinReg.hpp
        mainWidght/MklinkWidget.h
        Metadata/ContextMenu.h
        Metadata/TimeDuration.h
        Metadata/Comment.h
        Metadata/AssetsPath.h
)
set(
        DOODLELIB_SOURCE
        DoodleApp.cpp
        DoodleLib.cpp
        core/CoreSet.cpp
        core/CoreSql.cpp
        core/MetadataSet.cpp
        core/Name.cpp
        core/Ue4Setting.cpp
        FileSys/FileSystem.cpp
        FileWarp/ImageSequence.cpp
        FileWarp/MayaFile.cpp
        FileWarp/Ue4Project.cpp
        FileWarp/VideoSequence.cpp
        Logger/Logger.cpp
        mainWidght/mainWindows.cpp
        mainWidght/systemTray.cpp
        Metadata/Assets.cpp
        Metadata/AssetsFile.cpp
        Metadata/Episodes.cpp
        Metadata/Metadata.cpp
        Metadata/MetadataFactory.cpp
        Metadata/MetadataWidget.cpp
        Metadata/Project.cpp
        Metadata/Shot.cpp
        Metadata/Label/LabelNode.cpp
        Metadata/Model/AssstsTree.cpp
        Metadata/View/ShotListWidget.cpp
        PinYin/convert.cpp
        ScreenshotWidght/ScreenshotAction.cpp
        ScreenshotWidght/ScreenshotWidght.cpp
        Metadata/ContextMenu.cpp
        SettingWidght/settingWidget.cpp
        toolkit/MessageAndProgress.cpp
        toolkit/toolkit.cpp
        mainWidght/MklinkWidget.cpp
        Metadata/TimeDuration.cpp
        Metadata/Comment.cpp
        Metadata/AssetsPath.cpp

)
