set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET_VERSION 14.38)

if (PORT MATCHES "boost-process")
    set(VCPKG_CXX_FLAGS "-DBOOST_PROCESS_USE_STD_FS -DBOOST_DLL_USE_STD_FS")
    set(VCPKG_C_FLAGS "-DBOOST_PROCESS_USE_STD_FS -DBOOST_DLL_USE_STD_FS")
endif ()

if (PORT MATCHES "sqlite3")
    set(VCPKG_CXX_FLAGS "-DSQLITE_DEFAULT_MMAP_SIZE=0x3fff0000")
    set(VCPKG_C_FLAGS "")
endif ()