// generated by sqlpp11-ddl2cpp 005-assdepartment.sql assdepartment_sqlOrm doodle
#ifndef DOODLE_ASSDEPARTMENT_SQLORM_H
#define DOODLE_ASSDEPARTMENT_SQLORM_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace doodle
{
  namespace Assdepartment_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::bigint, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct AssDep
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ass_dep";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T assDep;
            T& operator()() { return assDep; }
            const T& operator()() const { return assDep; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::varchar, sqlpp::tag::can_be_null>;
    };
    struct ProjectId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "project_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T projectId;
            T& operator()() { return projectId; }
            const T& operator()() const { return projectId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::bigint, sqlpp::tag::can_be_null>;
    };
  } // namespace Assdepartment_

  struct Assdepartment: sqlpp::table_t<Assdepartment,
               Assdepartment_::Id,
               Assdepartment_::AssDep,
               Assdepartment_::ProjectId>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "assdepartment";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T assdepartment;
        T& operator()() { return assdepartment; }
        const T& operator()() const { return assdepartment; }
      };
    };
  };
} // namespace doodle
#endif
