// generated by sqlpp11-ddl2cpp 009-shottype.sql shottype_sqlOrm doodle
#ifndef DOODLE_SHOTTYPE_SQLORM_H
#define DOODLE_SHOTTYPE_SQLORM_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace doodle
{
  namespace Shottype_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::bigint, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct ShotType
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "shot_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T shotType;
            T& operator()() { return shotType; }
            const T& operator()() const { return shotType; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::varchar, sqlpp::tag::can_be_null>;
    };
    struct ShotClassId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "shotClass_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T shotClassId;
            T& operator()() { return shotClassId; }
            const T& operator()() const { return shotClassId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::bigint, sqlpp::tag::can_be_null>;
    };
    struct ProjectId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "project_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T projectId;
            T& operator()() { return projectId; }
            const T& operator()() const { return projectId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::bigint, sqlpp::tag::can_be_null>;
    };
  } // namespace Shottype_

  struct Shottype: sqlpp::table_t<Shottype,
               Shottype_::Id,
               Shottype_::ShotType,
               Shottype_::ShotClassId,
               Shottype_::ProjectId>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "shottype";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T shottype;
        T& operator()() { return shottype; }
        const T& operator()() const { return shottype; }
      };
    };
  };
} // namespace doodle
#endif
