set(
        DOODLELIB_HEADER
        core/ContainerDevice.h
        core/filesystem_extend.h
        core/observable_container.h
        core/image_loader.h
        core/authorization.h
        file_warp/opencv_read_player.h
        lib_warp/boost_locale_warp.h
        toolkit/toolkit.h
        exe_warp/maya_exe.h
        long_task/image_to_move.h
        long_task/join_move.h
        long_task/image_load_task.h
        doodle_lib_all.h
        doodle_lib_fwd.h
        doodle_lib_pch.h
)
set(
        DOODLELIB_SOURCE
        core/filesystem_extend.cpp
        core/image_loader.cpp
        core/authorization.cpp
        file_warp/opencv_read_player.cpp
        toolkit/toolkit.cpp
        exe_warp/maya_exe.cpp
        long_task/image_to_move.cpp
        long_task/join_move.cpp
        long_task/image_load_task.cpp
        doodle_lib_all.cpp
)
