message("CPACK_TOPLEVEL_DIRECTORY=${CPACK_TOPLEVEL_DIRECTORY}")
message("DOODLE_7z_NAME=${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}.7z")

set(DOODLE_7z_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME})
execute_process(
        COMMAND 7z a "${CPACK_TOPLEVEL_DIRECTORY}/${DOODLE_7z_NAME}.7z" "${CPACK_TOPLEVEL_DIRECTORY}/${DOODLE_7z_NAME}" -mx2 -mmt8
        COMMAND_ECHO STDOUT
)
execute_process(
        COMMAND ${CMAKE_COMMAND} -E copy ${CPACK_TOPLEVEL_DIRECTORY}/${DOODLE_7z_NAME}.7z ${CPACK_BUILD_SOURCE_DIRS}/${DOODLE_7z_NAME}.7z
)
