/**
 * This file was generated by bin2cpp v2.3.0
 * Copyright (C) 2013-2020 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file '_GlobalSettings.xml', last modified 1594172355.
 * Do not modify this file.
 */
#if defined(_WIN32) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS
#endif
#include "freeSynGlob.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class FreeSynGlobFile : public virtual bin2cpp::File
  {
  public:
    FreeSynGlobFile() { build(); }
    virtual ~FreeSynGlobFile() {}
    virtual size_t getSize() const { return 7264; }
    virtual const char * getFilename() const { return "_GlobalSettings.xml"; }
    virtual const char * getBuffer() const { return mBuffer.c_str(); }
    void build()
    {
      mBuffer.clear();
      mBuffer.reserve(getSize()); //allocate all required memory at once to prevent reallocations
      mBuffer.append("<\?xml version=\"1.0\" encoding=\"utf-8\"\?>\r\n<FreeFileSync XmlType=\"GLOBAL\" XmlFormat=\"16\">\r\n    <General>\r\n        <Language Name=\"Chinese (Simplified)\"/>\r\n        <FailSafeFileCopy Enabled=\"true\"/>\r\n    ", 200);
      mBuffer.append("    <CopyLockedFiles Enabled=\"false\"/>\r\n        <CopyFilePermissions Enabled=\"false\"/>\r\n        <FileTimeTolerance Seconds=\"2\"/>\r\n        <RunWithBackgroundPriority Enabled=\"true\"/>\r\n        <LockDire", 200);
      mBuffer.append("ctoriesDuringSync Enabled=\"true\"/>\r\n        <VerifyCopiedFiles Enabled=\"true\"/>\r\n        <LogFiles MaxAge=\"30\" Format=\"HTML\"/>\r\n        <NotificationSound CompareFinished=\"\" SyncFinished=\"%ffs_resourc", 200);
      mBuffer.append("e%\\bell.wav\"/>\r\n        <ProgressDialog AutoClose=\"false\"/>\r\n        <OptionalDialogs>\r\n            <ConfirmStartSync Show=\"false\"/>\r\n            <ConfirmSaveConfig Show=\"false\"/>\r\n            <Confir", 200);
      mBuffer.append("mCommandMassInvoke Show=\"false\"/>\r\n            <WarnFolderNotExisting Show=\"false\"/>\r\n            <WarnFoldersDifferInCase Show=\"false\"/>\r\n            <WarnUnresolvedConflicts Show=\"true\"/>\r\n         ", 200);
      mBuffer.append("   <WarnNotEnoughDiskSpace Show=\"true\"/>\r\n            <WarnSignificantDifference Show=\"false\"/>\r\n            <WarnRecycleBinNotAvailable Show=\"false\"/>\r\n            <WarnInputFieldEmpty Show=\"false\"/>", 200);
      mBuffer.append("\r\n            <WarnModificationTimeError Show=\"false\"/>\r\n            <WarnDependentFolderPair Show=\"false\"/>\r\n            <WarnDependentBaseFolders Show=\"false\"/>\r\n            <WarnDirectoryLockFailed", 200);
      mBuffer.append(" Show=\"false\"/>\r\n            <WarnVersioningFolderPartOfSync Show=\"false\"/>\r\n        </OptionalDialogs>\r\n    </General>\r\n    <Gui>\r\n        <MainDialog Width=\"1368\" Height=\"766\" PosX=\"230\" PosY=\"530\" ", 200);
      mBuffer.append("Maximized=\"true\">\r\n            <SearchPanel CaseSensitive=\"false\"/>\r\n            <ConfigPanel ScrollPos=\"0\" SyncOverdue=\"7\" SortByColumn=\"Name\" SortAscending=\"true\">\r\n                <Columns>\r\n      ", 200);
      mBuffer.append("              <Item Type=\"Name\" Visible=\"true\" Width=\"-107\" Stretch=\"1\"/>\r\n                    <Item Type=\"Last\" Visible=\"true\" Width=\"65\" Stretch=\"0\"/>\r\n                    <Item Type=\"Log\" Visible=\"", 200);
      mBuffer.append("true\" Width=\"42\" Stretch=\"0\"/>\r\n                </Columns>\r\n                <Configurations MaxSize=\"100\">\r\n                    <Item Result=\"Warning\" Config=\"FFS:\\Users\\teXiao\\AppData\\Roaming\\FreeFil", 200);
      mBuffer.append("eSync\\LastRun.ffs_gui\" LastSync=\"1590031450\" Log=\"FFS:\\Users\\teXiao\\AppData\\Roaming\\FreeFileSync\\Logs\\[\346\234\200\345\220\216\344\274\232\350\257\235] 2020-05-21 112410.120 [\350\255\246\345\221\212].html\" Color=\"DDDDDD\"/>\r\n                </Configurat", 200);
      mBuffer.append("ions>\r\n                <LastUsed>\r\n                    <Item>FFS:\\Users\\teXiao\\AppData\\Roaming\\FreeFileSync\\LastRun.ffs_gui</Item>\r\n                </LastUsed>\r\n            </ConfigPanel>\r\n           ", 200);
      mBuffer.append(" <OverviewPanel ShowPercentage=\"true\" SortByColumn=\"Bytes\" SortAscending=\"false\">\r\n                <Columns>\r\n                    <Item Type=\"Tree\" Visible=\"true\" Width=\"-120\" Stretch=\"1\"/>\r\n         ", 200);
      mBuffer.append("           <Item Type=\"Count\" Visible=\"true\" Width=\"60\" Stretch=\"0\"/>\r\n                    <Item Type=\"Bytes\" Visible=\"true\" Width=\"60\" Stretch=\"0\"/>\r\n                </Columns>\r\n            </Overvie", 200);
      mBuffer.append("wPanel>\r\n            <FilePanel ShowIcons=\"true\" IconSize=\"Small\" SashOffset=\"2\" FolderPairsMax=\"8\">\r\n                <ColumnsLeft PathFormat=\"Relative\">\r\n                    <Item Type=\"Path\" Visible", 200);
      mBuffer.append("=\"true\" Width=\"324\" Stretch=\"1\"/>\r\n                    <Item Type=\"Ext\" Visible=\"false\" Width=\"60\" Stretch=\"0\"/>\r\n                    <Item Type=\"Date\" Visible=\"false\" Width=\"110\" Stretch=\"0\"/>\r\n     ", 200);
      mBuffer.append("               <Item Type=\"Size\" Visible=\"true\" Width=\"336\" Stretch=\"0\"/>\r\n                </ColumnsLeft>\r\n                <FolderHistoryLeft>\r\n                </FolderHistoryLeft>\r\n                <C", 200);
      mBuffer.append("olumnsRight PathFormat=\"Relative\">\r\n                    <Item Type=\"Path\" Visible=\"true\" Width=\"18\" Stretch=\"1\"/>\r\n                    <Item Type=\"Ext\" Visible=\"false\" Width=\"60\" Stretch=\"0\"/>\r\n      ", 200);
      mBuffer.append("              <Item Type=\"Date\" Visible=\"false\" Width=\"110\" Stretch=\"0\"/>\r\n                    <Item Type=\"Size\" Visible=\"true\" Width=\"336\" Stretch=\"0\"/>\r\n                </ColumnsRight>\r\n            ", 200);
      mBuffer.append("    <FolderHistoryRight>\r\n                </FolderHistoryRight>\r\n            </FilePanel>\r\n            <ManualCopyTo KeepRelativePaths=\"false\" OverwriteIfExists=\"false\">\r\n                <FolderHistor", 200);
      mBuffer.append("y LastUsedPath=\"\"/>\r\n            </ManualCopyTo>\r\n            <DefaultViewFilter Equal=\"false\" Conflict=\"true\" Excluded=\"false\">\r\n                <CategoryView LeftOnly=\"true\" RightOnly=\"true\" LeftNew", 200);
      mBuffer.append("er=\"true\" RightNewer=\"true\" Different=\"true\"/>\r\n                <ActionView CreateLeft=\"true\" CreateRight=\"true\" UpdateLeft=\"true\" UpdateRight=\"true\" DeleteLeft=\"true\" DeleteRight=\"true\" DoNothing=\"tr", 200);
      mBuffer.append("ue\"/>\r\n            </DefaultViewFilter>\r\n            <Perspective>layout2|name=CenterPanel;caption=;state=256;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=624;besth=61;minw=-1;minh=-1;maxw=-1;maxh=-1;f", 200);
      mBuffer.append("loatx=-1;floaty=-1;floatw=-1;floath=-1|name=TopPanel;caption=\344\270\273\345\267\245\345\205\267\346\240\217;state=2099708;dir=1;layer=2;row=1;pos=0;prop=100000;bestw=588;besth=51;minw=170;minh=51;maxw=-1;maxh=-1;floatx=-1;floaty=-1;fl", 200);
      mBuffer.append("oatw=-1;floath=-1|name=ProgressPanel;caption=;state=2097662;dir=1;layer=2;row=2;pos=0;prop=100000;bestw=532;besth=102;minw=-1;minh=102;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=Fold", 200);
      mBuffer.append("ersPanel;caption=\346\226\207\344\273\266\345\244\271\345\257\271;state=2099708;dir=1;layer=2;row=3;pos=0;prop=100000;bestw=622;besth=50;minw=-1;minh=50;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=SearchPanel;caption=\346\237", 200);
      mBuffer.append("\245\346\211\276;state=2099710;dir=3;layer=2;row=3;pos=0;prop=100000;bestw=247;besth=27;minw=100;minh=27;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=LogPanel;caption=\346\227\245\345\277\227;state=6293500;dir=3;la", 200);
      mBuffer.append("yer=2;row=2;pos=0;prop=100000;bestw=600;besth=300;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=ViewFilterPanel;caption=\350\247\206\345\233\276\350\256\276\347\275\256;state=2099708;dir=3;layer=2;row=1;po", 200);
      mBuffer.append("s=0;prop=100000;bestw=479;besth=49;minw=100;minh=49;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=ConfigPanel;caption=\351\205\215\347\275\256;state=2099196;dir=4;layer=3;row=0;pos=0;prop=100000;bestw=20", 200);
      mBuffer.append("8;besth=57;minw=188;minh=57;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=OverviewPanel;caption=\346\221\230\350\246\201;state=2099196;dir=4;layer=3;row=0;pos=1;prop=100000;bestw=300;besth=20;minw=-1;min", 200);
      mBuffer.append("h=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=187|dock_size(1,2,1)=51|dock_size(1,2,3)=50|dock_size(3,2,1)=49|dock_size(4,3,0)=251|dock_size(3,2,2)=318|</Perspective>\r\n", 200);
      mBuffer.append("        </MainDialog>\r\n        <DefaultExclusionFilter>\r\n            <Item>\\System Volume Information\\</Item>\r\n            <Item>\\$Recycle.Bin\\</Item>\r\n            <Item>\\RECYCLE\?\\</Item>\r\n           ", 200);
      mBuffer.append(" <Item>*\\desktop.ini</Item>\r\n            <Item>*\\thumbs.db</Item>\r\n        </DefaultExclusionFilter>\r\n        <FolderHistory MaxSize=\"20\"/>\r\n        <VersioningFolderHistory>\r\n        </VersioningFold", 200);
      mBuffer.append("erHistory>\r\n        <LogFolderHistory/>\r\n        <EmailHistory MaxSize=\"10\"/>\r\n        <CommandHistory MaxSize=\"10\"/>\r\n        <ExternalApps>\r\n            <Item Label=\"Show in Explorer\">explorer /sele", 200);
      mBuffer.append("ct, \"%local_path%\"</Item>\r\n            <Item Label=\"Open with default application\">\"%local_path%\"</Item>\r\n        </ExternalApps>\r\n        <LastOnlineCheck>13919</LastOnlineCheck>\r\n        <LastOnline", 200);
      mBuffer.append("Version>10.24</LastOnlineVersion>\r\n    </Gui>\r\n</FreeFileSync>\r\n", 64);
    }
    virtual bool save(const char * iFilename) const
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t fileSize = getSize();
      const char * buffer = getBuffer();
      fwrite(buffer, 1, fileSize, f);
      fclose(f);
      return true;
    }
  private:
    std::string mBuffer;
  };
  const File & getFreeSynGlobFile() { static FreeSynGlobFile _instance; return _instance; }
}; //bin2cpp
